name: Build File Organizer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Windows build tools
      run: |
        npm config set msvs_version 2019

    - name: Build Next.js app
      run: |
        npm run build
      env:
        CI: false

    - name: Build Electron app
      run: |
        npm run electron:build
      env:
        CI: false

    - name: Upload Windows Installer
      uses: actions/upload-artifact@v2.3.1
      with:
        name: file-organizer-installer
        path: dist/*.exe
        retention-days: 30

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
        tag_name: v${{ github.run_number }}
        name: File Organizer v${{ github.run_number }}
        body: |
          ## File Organizer Release

          Automated build from the latest code.

          ### Installation
          1. Download the installer
          2. Run the installer
          3. Launch the application from your Start menu

          ### Changes
          - Latest updates from the main branch
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
